//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEmpleados23.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleado
    {
        
        public string Codigo { get; set; }
        
        [Required]
        [StringLength(50)]
        public string Nombres { get; set; }
        
        [Required]
        [StringLength(50)]
        public string Apellidos { get; set; }
        
        [DataType(DataType.Date)]
        [Display(Name = "Fecha Nacimiento")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}",ApplyFormatInEditMode =true)]
        public Nullable<System.DateTime> Fecha_n { get; set; }
        
        [Required]
        public string Departamento { get; set; }
    
        public virtual Departamento Departamento1 { get; set; }
    }
}
